### ISSUE TITLE
Use a style guide.

### ISSUE THREAD

**Issue by TobiasSN** [bitphoenixsoftware/cassian#3]
There are a few places in the code where the code style is inconsistent. For example, in `routes/users.js`:
```js
/*61*/    .exec(async function(err, user) {
/*62*/        if(user)
/*63*/        {
/*64*/          res.locals.profile = user;
```
I can see two problems:

1. On line 63, the curly brace is on its own line. Not only is this **very** uncommon in JS, it's inconsistent with the one on 61, which shares it with the function definition.
2. Let's compare the indentation level of each line to the amount of spaces it has:

| Line | Indentation level | Spaces |
| --- | --- | --- |
| 61 | 2 | 4 |
| 62 | 3 | 8 |
| 63 | 3 | 8 |
| 64 | 4 | 10 |

Let's analyze this. Line 61 is at indentation level 2, and has 4 spaces, so we can assume that for each indentation level there's two spaces. So since line 62 and 63 is at indentation level 3, it must have 6 spaces. However, it has 8. That's an increase of 4 spaces. When we then go to line 64 which is at indentation level 4, it has an increase of two spaces. So there's basically no rule for how much whitespace you should have.

**The solution**

As the title says, Cassian should have a style guide. These are used an almost every JS project, and they allow people to write consistent code. A style guide is a set of rules for how code should be formatted, and they are often used together with a linter like ESLint. Some even have a dedicated tool to make using them much easier.

**Suggestions**

There are tons of style guides to choose from, but I'll list a few:

- [StandardJS](https://standardjs.com)
  - There are also quite a few based on this [here](https://github.com/standard/awesome-standard#forks).
- [Airbnb](https://github.com/airbnb/javascript)
- [Google](https://google.github.io/styleguide/jsguide.html)
- Or even my own, [Wiw](https://github.com/TobiasSN/wiw)

**Comment by TheDarkBomber** [comment]
n o

**Comment by alkalinethunder** [comment]
Closing due to this project being deprecated in favor of the rewrite.
